name: Validate Application Deployment Info
description: Validates that the deployment information for an application exists

inputs:
  compute-target:
    description: The compute target (ECS or Lambda)
    required: true
  ecs-cluster-name:
    description: The ECS Cluster Name
    required: false
  ecs-service-name:
    description: The ECS Service Name
    required: false
  lambda-function-name:
    description: The Lambda Function Name
    required: false

runs:
  using: composite
  steps:
    - name: Validate ECS Info
      if: ${{ inputs.compute-target == 'ecs' }}
      shell: bash
      run: |
        ECS_FAIURES=$(aws ecs describe-services {
          --cluster "${{ inputs.ecs-cluster-name }}" \
          --services "${{ inputs.ecs-service-name}}" \
          --query 'failures')
        if [ "$ECS_FAIURES" != "[]" ]; then
          echo "ECS Service ${{ inputs.ecs-service-name }} in cluster ${{ inputs.ecs-cluster-name }} does not exist."
          echo "::debug::Failures: $ECS_FAIURES"
          exit 1
        fi

    - name: Validate Lambda Info
      if: ${{ inputs.compute-target == 'lambda' }}
      shell: bash
      run: |
        aws lambda get-function --function-name "${{ inputs.lambda-function-name }}"
