name: Terraform Action
description: Run terraform

inputs:
  terraform-command:
    required: true
    description: The Terraform command to run
  terraform-use-backend:
    required: false
    description: 'Whether to use a backend configuration for Terraform.'
    default: "true"
  terraform-options:
    required: false
    description: 'The options to use in the Terraform configuration.'
    default: ""
  fail-on-exit-code:
    required: false
    description: 'Whether to fail the action if the Terraform command exits with a non-zero exit code.'
    default: "true"
  always-run-init:
    required: false
    description: 'Whether to always run terraform init.'
    default: "false"
  working-directory:
    description: "Directory containing the project files"
    required: false
    default: "."
  terraform-directory:
    description: "Directory where Terraform environment directories are located"
    required: true
  env-mapping-directory:
    description: "Which environment directory to use"
    required: true
  git-sha:
    required: false
    description: "Git SHA to use for versioning"
    default: ${{ github.event.pull_request.head.sha || github.sha }}

outputs:
  exitcode:
    description: 'The exit code of the Terraform command.'
    value: ${{ steps.terraform.outputs.exitcode }}
  stdout:
    description: 'The standard output of the Terraform command.'
    value: ${{ steps.terraform.outputs.stdout }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Determine Terraform directory (terraform or environment)
      id: tf-dir
      shell: bash
      run: |
        echo "Working directory: ${{ inputs.working-directory }}"
        if [[ -n "${{ inputs.terraform-directory }}" ]]; then
          echo "dir=${{inputs.working-directory}}/${{ inputs.terraform-directory }}/${{ inputs.env-mapping-directory }}" >> $GITHUB_OUTPUT
        elif [ -d "${{ inputs.working-directory }}/environments/${{ inputs.env-mapping-directory }}" ]; then
          echo "dir=${{inputs.working-directory}}/environments/${{ inputs.env-mapping-directory }}" >> $GITHUB_OUTPUT
        elif [ -d "${{ inputs.working-directory }}/terraform/${{ inputs.env-mapping-directory }}" ]; then
          echo "dir=${{inputs.working-directory}}/terraform/${{ inputs.env-mapping-directory }}" >> $GITHUB_OUTPUT
        else
          echo "No valid Terraform directory found"
          exit 1
        fi

    - name: Find Terraform version
      shell: bash
      run: |
        set -e
        dirs=(
          "${{ steps.tf-dir.outputs.dir }}"
          "${{ inputs.working-directory }}/infrastructure"
          "${{ inputs.working-directory }}/terraform/template"
          "${{ inputs.working-directory }}/terraform"
        )
        echo "Searching for Terraform version in directories: ${dirs[*]}"
        for dir in "${dirs[@]}"; do
          echo "Checking directory: $dir"
          if [ -d "$dir" ]; then
            version=$(grep -rEho 'required_version *= *"[^"]+"' "$dir" --include \*.tf | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | head -n1 || true)
            if [ -n "$version" ]; then
              echo "Found Terraform version: $version"
              echo "TERRAFORM_VERSION=$version" >> $GITHUB_ENV
              exit 0
            fi
          fi
        done
        echo "::error title=Terraform version not found::Could not determine required Terraform version."
        exit 1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Cache Terraform
      id: terraform-cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/${{ steps.tf-dir.outputs.dir }}/.terraform
        key: ${{runner.os}}-${{ steps.tf-dir.outputs.dir }}-terraform-${{ inputs.git-sha }}
        restore-keys: |
          ${{runner.os}}-${{ steps.tf-dir.outputs.dir }}-terraform-

    - name: Terraform Init
      if: steps.restore-terraform.outputs.cache-hit == 'false' || inputs.always-run-init == 'true'
      shell: bash
      working-directory: ${{ steps.tf-dir.outputs.dir }}
      run: |
        set -e
        terraform init --backend=${{ inputs.terraform-use-backend }}

    - name: Terraform Command
      working-directory: ${{ steps.tf-dir.outputs.dir }}
      id: terraform
      shell: bash
      run: terraform ${{ inputs.terraform-command }} ${{ inputs.terraform-options }}

    - name: Terraform Output
      continue-on-error: ${{ inputs.fail-on-exit-code == 'false' }}
      shell: bash
      run: |
        if [ "${{ steps.terraform.outputs.exitcode }}" = "1" ]; then
          echo "Terraform failed with an error."
        elif [ "${{ steps.terraform.outputs.exitcode }}" = "2" ]; then
          echo "Terraform succeeded with changes present."
        else
          echo "Terraform exited with an unexpected code: ${{ steps.terraform.outputs.exitcode }}"
        fi
