name: Publish DORA Metric
description: Publishes status to DORA Metric Handler

inputs:
  status:
    description: "The status of the pipeline to report to the metric handler (started | failed | succeeded)"
    required: true
  topic_arn:
    description: "The DORA Metric Report SNS Topic ARN"
    required: true

runs:
  using: composite
  steps:
    - name: Send SNS message
      id: sns-message
      shell: bash
      env:
        GIT_REPO: ${{ github.event.repository.name }}
        COMMIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
        COMMIT_MESSAGE: ${{ github.event.pull_request.title || github.event.head_commit.message }}
      run: |
        timestamp=$(date +%s)
        deploy_id="${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"

        # Get AWS account ID
        aws_account_id=$(aws sts get-caller-identity --query Account --output text)

        message=$(cat << EOF
        {
          "time": ${timestamp},
          "account_id": "${aws_account_id}",
          "git_repo": "${GIT_REPO}",
          "pipeline": "${GIT_REPO}",
          "status": "${{ inputs.status }}",
          "commit_hash": "${COMMIT_HASH}",
          "commit_message": "${COMMIT_MESSAGE}",
          "deploy_id": "${deploy_id}",
          "provider": "github"
        }
        EOF
        )

        echo "Sending deployment status to SNS topic"
        aws sns publish \
          --topic-arn ${{ inputs.topic_arn }} \
          --message "$message"

        echo "Message sent successfully"