inputs:
  function-name:
    description: "The name of the Lambda Function"
    required: true
  image-uri:
    description: "The ECR image URI to deploy"
    required: true
  aws-region:
    description: "The AWS Region to use for the deployment"
    required: true
    default: "eu-west-1"

runs:
  using: composite
  steps:
    - name: Get current environment variables
      id: env-vars
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        aws lambda get-function-configuration --function-name "${{ inputs.function-name }}" --query 'Environment.Variables' --output json > env-vars.json

    - name: Update Lambda Environment Variables with DD Tags
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        ENV_VARS=$(cat env-vars.json)
        
        # Check if any existing variables begin with "DD_"
        HAS_DD_VARS=$(echo $ENV_VARS | jq 'keys[] | select(startswith("DD_"))' | wc -l)
        
        if [ "$HAS_DD_VARS" -gt 0 ] || [ -z "$ENV_VARS" ] || [ "$ENV_VARS" = "{}" ]; then
          COMMIT_SHA="${{ github.event.pull_request.head.sha || github.sha }}"
          REPO_URL="${{ github.server_url }}/${{ github.repository }}"
          
          UPDATED_ENV_VARS=$(echo $ENV_VARS | jq '. + {
            DD_VERSION: "'$COMMIT_SHA'",
            DD_GIT_COMMIT_SHA: "'$COMMIT_SHA'",
            DD_GIT_REPOSITORY_URL: "'$REPO_URL'"
          }')
          
          ENV_JSON=$(echo '{"Variables": '$UPDATED_ENV_VARS'}')
          aws lambda update-function-configuration --function-name "${{ inputs.function-name }}" --environment "$ENV_JSON"
        else
          echo "Datadog not enabled. Skipping environment variable update."
        fi

    - name: Publish Lambda Version and Update Version Tag
      id: publish
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        LAMBDA_NAME="${{ inputs.function-name }}"
        IMAGE_URI="${{ inputs.image-uri }}"

        NEW_LAMBDA_VERSION=$(aws lambda update-function-code --function-name $LAMBDA_NAME --image-uri $IMAGE_URI --query 'Version' --publish --output text)

        echo "new_lambda_version=$NEW_LAMBDA_VERSION" >> $GITHUB_OUTPUT

    - name: Update Lambda Alias to New Version
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        aws lambda update-alias --function-name "${{ inputs.function-name }}" --name active --function-version "${{ steps.publish.outputs.new_lambda_version }}"
