name: Upload Build to S3 with SHA

inputs:
  # TODO: Need to decide whether it should be the hardcoded same artifact name and path as upload
  artifact-name:
    description: "Name of the artifact storing the build files."
    required: false
    default: "node-artifact"
  artifact-path:
    description: "Path to artifact files from previous workflow."
    required: false
    default: "build"
  s3-bucket-name:
    description: "Name of the bucket to upload static files to."
    required: true

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}

    - name: Upload build files to S3
      shell: bash
      id: upload
      run: |
          aws s3 cp --recursive ${{ inputs.artifact-path }} s3://${{ inputs.s3-bucket-name }}/${{ github.sha }}
