name: Upload Build to S3 with SHA

inputs:
  # TODO: Need to decide whether it should be the hardcoded same artifact name and path as upload
  artifact-name:
    description: "Name of the artifact storing the build files."
    required: false
    default: "node-artifact"
  artifact-path:
    description: "Path to artifact files from previous workflow."
    required: false
    default: "build/client" # Default path to the client build files
  s3-bucket-name:
    description: "Name of the bucket to upload static files to."
    required: true
  git-sha:
    required: true
    description: "Git SHA to use for versioning"
  s3-static-files-path:
    description: "Path in S3 bucket to upload static files to."
    required: false
    default: "static"
  cache-control-config:
    description: "Path to cache-control config file (relative to repository root)"
    required: false
    default: ".static-files-cache.yml"

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}

    - name: Install Python dependencies
      shell: bash
      run: |
        python3 -m pip install -q boto3 PyYAML

    - name: Upload build files to S3
      shell: bash
      id: upload
      run: |
          python3 ${{ github.action_path }}/upload.py \
            "${{ inputs.artifact-path }}" \
            "${{ inputs.s3-bucket-name }}" \
            "${{ inputs.s3-static-files-path }}/${{ inputs.git-sha }}" \
            "${{ inputs.cache-control-config }}"
