name: Datadog CI
description: |
  Run a `datadog-ci` command using the official Docker image.
  AWS credentials must be configured before calling this action.

inputs:
  command:
    description: 'The datadog-ci command to run (e.g. "sourcemaps upload ./dist --service my-app --release-version 1.0.0")'
    required: true
  datadog-site:
    description: 'Datadog site. Defaults to EU'
    required: false
    default: 'datadoghq.eu'
  datadog-ci-version-sha:
    required: false
    description: 'Version of datadog-ci to use'
    default: 'sha256:d7f52e5bef68fe283683824b41e3630274aacc8ac2540b0004eb334ebcf3e507'
  api-key-secret-id:
    description: 'Pass `vars.DATADOG_CI_API_KEY_SECRET_ID` from your workflow. Is the name of the Secret in Secrets Manager, where the api key lives'
    required: true
  git-commit-sha:
    description: 'Git commit SHA to associate with the upload'
    required: false
    default: ${{ github.event.pull_request.head.sha || github.sha }}
  git-repository-url:
    description: 'URL of the repository'
    required: false
    default: ${{ github.server_url }}/${{ github.repository }}

runs:
  using: composite
  steps:
    - uses: nsbno/platform-actions/.github/actions/helpers/aws/fetch-secrets-from-secrets-manager@working-datadog-ci
      id: api-key
      with:
        secret-id: ${{ inputs.api-key-secret-id }}

    - name: Run datadog-ci
      shell: bash
      env:
        DATADOG_API_KEY: ${{ steps.api-key.outputs.secret-value }}
        DATADOG_SITE: ${{ inputs.datadog-site }}
        DD_GIT_COMMIT_SHA: '${{ inputs.git-commit-sha }}'
        DD_GIT_REPOSITORY_URL: '${{ inputs.git-repository-url }}'
      run: |
        docker run --rm \
          -e DATADOG_API_KEY \
          -e DATADOG_SITE \
          -e DD_GIT_COMMIT_SHA \
          -e DD_GIT_REPOSITORY_URL \
          -e GIT_CONFIG_COUNT=1 \
          -e GIT_CONFIG_KEY_0=safe.directory \
          -e GIT_CONFIG_VALUE_0=/workspace \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          public.ecr.aws/datadog/ci@${{ inputs.datadog-ci-version-sha }} \
          ${{ inputs.command }}
