name: NPM
description: Run any npm commands from working-directory. Will make sure any dependencies are installed first.

inputs:
  NEXUS_USERNAME:
    required: true
    description: "Nexus login username."
  NEXUS_PASSWORD:
    required: true
    description: "Nexus login password."

  node-version:
    required: true
    description: "What Node.js version to use."
  npm-operations:
    required: true
    description: "NPM operations to run."
  working-directory:
    required: false
    default: "."
    description: "Where NPM will be run from."
  git-sha:
    required: true
    description: "Git SHA to use for versioning"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

    - name: Authenticate with Nexus repository
      shell: bash
      env:
        NEXUS_USERNAME: ${{ inputs.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ inputs.NEXUS_PASSWORD }}
      run: |
        TOKEN=$(echo -n $NEXUS_USERNAME:$NEXUS_PASSWORD | base64)
        npm config set "//nexus.common-services.vydev.io/repository/npm-group/:_auth=$TOKEN"

    - name: Run NPM Install
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        NEXUS_USERNAME: ${{ inputs.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ inputs.NEXUS_PASSWORD }}
      run: |
        npm ci

    - name: Run NPM Command
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        npm-operations: ${{ inputs.npm-operations }}
        NEXUS_USERNAME: ${{ inputs.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ inputs.NEXUS_PASSWORD }}
        GIT_SHA: ${{ inputs.git-sha }}
      run: |
        npm run ${{ inputs.npm-operations }}
