name: Any Terraform Changes?

inputs:
  environment:
    description: The current environment
    required: true
  aws-region:
    description: The AWS region to use.
    required: true
  aws-account-id:
    description: The AWS account ID for deployment.
    required: true
  deployment-role:
    description: The AWS role to assume for deployment.
    required: true
  working-directory:
    description: "Directory containing the project files"
    required: true
  terraform-directory:
    description: Directory where Terraform environment directories are located
    required: true
  terraform-options:
    description: 'The options to use in the Terraform configuration.'
    required: false
    default: ''

outputs:
  any-changed:
    description: 'Whether any Terraform changes are pending.'
    value: ${{ steps.terraform.outputs.exitcode == 2 }}
  stdout:
    description: 'The standard output of the Terraform command.'
    value: ${{ steps.terraform.outputs.stdout }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate with AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: "arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.deployment-role }}"

    - uses: nsbno/platform-actions/.github/actions/helpers/environment-mapping@main
      id: env-mapping
      with:
        environment: ${{ inputs.environment }}

    - uses: nsbno/platform-actions/.github/actions/tools/terraform@main
      id: terraform
      with:
        directory: '${{inputs.working-directory}}/${{inputs.terraform-directory}}/${{ steps.env-mapping.outputs.directory }}'
        working-directory: ${{ inputs.working-directory }}
        terraform-command: plan --refresh=false -detailed-exitcode
        fail-on-exit-code: 'true'
        always-run-init: 'true'
        terraform-options: ${{ inputs.terraform-options }}
