name: Push Mapping to DynamoDB
description: Push mapping of preview URL to App Runner URL to DynamoDB

inputs:
  domain-name:
    description: "The domain name to use for the service"
    required: true
  apprunner-host:
    description: "The App Runner URL to map"
    required: true
  dynamodb-table-arn:
    description: "The name of the DynamoDB table to push the mapping to"
    required: true
  github-token:
    description: "GitHub token to use for commenting on the PR"
    required: true

runs:
  using: composite
  steps:
    - name: Push mapping to DynamoDB
      shell: bash
      run: |
        aws dynamodb put-item \
        --table-name "${{ inputs.dynamodb-table-arn }}" \
        --item '{
          "domain": {"S": "'${{ inputs.domain-name }}'"},
          "apprunner_host": {"S": "'${{ inputs.apprunner-host }}'"},
          "timestamp": {"N": "'$(date -u -d "+7 days" +%s)'"}
        }' \
        --region us-east-1

    - name: Comment on PR with Domain Name
      shell: bash
      run: |
        DOMAIN_NAME="https://${{ inputs.domain-name }}"
  
        # Create the comment body with proper JSON escaping
        COMMENT_BODY=$(cat <<EOF
          ## Preview Deployment Information
    
          Your preview environment has been deployed successfully! 🚀
    
          **Preview Domain Name:** ${DOMAIN_NAME}
        EOF
        )
        
        ISSUE_NUMBER="${{ github.event.pull_request.number }}"
        GITHUB_REPOSITORY="${{ github.repository }}"

        gh api \
          --method POST \
          repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
          -f body="${COMMENT_BODY}"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
