inputs:
  function-name:
    description: "The name of the Lambda Function"
    required: true
  artifact-name:
    description: "The name of the artifact to download from the build"
    required: true
    default: "lambda-artifact"
  aws-region:
    description: "The AWS Region to use for the deployment"
    required: true
    default: "eu-west-1"

runs:
  using: composite
  steps:
    - name: Download artifacts from build
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}

    - name: zip artifact
      id: zip
      shell: bash
      run: |
        echo "Zipping artifact into ${{ inputs.function-name }}.zip"
        zip -r "./${{ inputs.function-name }}.zip" ./*

    - name: Resolve artifacts S3 bucket
      id: resolve-bucket
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        echo "S3_BUCKET=${ACCOUNT_ID}-deployment-delivery-pipeline-artifacts" >> $GITHUB_ENV

    - name: Upload to S3
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
        GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        APPLICATION_NAME: ${{ inputs.function-name }}
        ZIP_FILE_NAME: "${{ inputs.function-name }}.zip"
      run: |
        BRANCH=$(echo $GITHUB_REF | cut -f3 -d/)

        aws s3 cp "./$ZIP_FILE_NAME" "s3://$S3_BUCKET/$APPLICATION_NAME/$GIT_SHA.zip" --metadata "tags"="'[\"${GIT_SHA}-SHA\",\"${BRANCH}-branch\"]'"
        aws s3 cp "./$ZIP_FILE_NAME" "s3://$S3_BUCKET/$APPLICATION_NAME/$BRANCH.zip" --metadata "tags"="'[\"${GIT_SHA}-SHA\",\"${BRANCH}-branch\"]'"

    - name: Publish Lambda Version
      id: publish
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        LAMBDA_NAME="${{ inputs.function-name }}"
        S3_KEY_PATH="$LAMBDA_NAME/${{ github.event.pull_request.head.sha || github.sha }}.zip"
        
        NEW_LAMBDA_VERSION=$(aws lambda update-function-code \
          --function-name $LAMBDA_NAME \
          --s3-bucket $S3_BUCKET \ 
          --s3-key $S3_KEY_PATH \
          --query 'Version' --publish --output text)
        
        echo "new_lambda_version=$NEW_LAMBDA_VERSION" >> $GITHUB_OUTPUT

    - name: Update Lambda Alias to New Version
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        aws lambda update-alias --function-name "${{ inputs.function-name }}" --name active --function-version "${{ steps.publish.outputs.new_lambda_version }}"
