inputs:
  function-name:
    description: "The name of the Lambda Function"
    required: true
  lambda-s3-bucket:
    description: "The S3 Bucket to upload the Lambda package to"
    required: true
  aws-region:
    description: "The AWS Region to use for the deployment"
    required: true
    default: "eu-west-1"

runs:
  using: composite
  steps:
    - name: Publish Lambda Version
      id: publish
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        LAMBDA_NAME="${{ inputs.function-name }}"
        S3_BUCKET="${{ inputs.lambda-s3-bucket }}"
        S3_KEY_PATH="$LAMBDA_NAME/${{ github.event.pull_request.head.sha || github.sha }}.zip"
        
        NEW_LAMBDA_VERSION=$(aws lambda update-function-code \
          --function-name $LAMBDA_NAME \
          --s3-bucket $S3_BUCKET \ 
          --s3-key $S3_KEY_PATH \
          --query 'Version' --publish --output text)
        
        echo "new_lambda_version=$NEW_LAMBDA_VERSION" >> $GITHUB_OUTPUT

    - name: Update Lambda Alias to New Version
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        aws lambda update-alias --function-name "${{ inputs.function-name }}" --name active --function-version "${{ steps.publish.outputs.new_lambda_version }}"
