name: Bump Lambda Version in SSM Parameter Store

inputs:
  sha-to-deploy:
    description: "The SHA to deploy. Defaults to the current commit SHA."
    required: true
  working-directory:
    description: "Directory containing the project files"
    required: true
  github-repo-name:
    description: "GitHub repository name"
    required: true

runs:
  using: composite
  steps:
    - name: Conditional SSM Parameter Update for Lambda Version
      shell: bash
      env:
        SHA_TO_DEPLOY: ${{ inputs.sha-to-deploy }}
        REPO_NAME: ${{ inputs.github-repo-name }}
        SERVICE_DIR: ${{ inputs.working-directory }}
      run: |
        REPO_NAME_WITHOUT_OWNER="${REPO_NAME##*/}"
        if [ "$SERVICE_DIR" == "." ]; then
          SERVICE_DIR="base"
        else
          SERVICE_DIR="${SERVICE_DIR##*/}"
        fi
        PARAMETER_NAME="/__deployment__/${REPO_NAME_WITHOUT_OWNER}/${SERVICE_DIR}/lambda_version"

        # Check if parameter exists and update it
        if aws ssm get-parameter --name "$PARAMETER_NAME" --query 'Parameter.Value' --output text 2>/dev/null; then
          echo "Parameter $PARAMETER_NAME exists, updating to $SHA_TO_DEPLOY"
          aws ssm put-parameter \
            --name "$PARAMETER_NAME" \
            --value "$SHA_TO_DEPLOY" \
            --type String \
            --overwrite
        echo "Updated SSM parameter for Lambda version"
        else
          echo "Parameter $PARAMETER_NAME does not exist yet, skipping (Terraform will create it if deploying Lambda)"
        fi