name: Put Application Deployment Info
description: Puts information about the version of the application being deployed

inputs:
  ecs-service-name:
    description: "The name of the application"
  sha-to-deploy:
    description: "The SHA to deploy"

runs:
  using: composite
  steps:
    - name: Put Version Parameter
      id: params
      shell: bash
      run: |
        aws ssm put-parameter --name "/__platform__/versions/${{ inputs.ecs-service-name }}" --value "${{ inputs.sha-to-deploy }}" --type String --tier Standard --overwrite
