name: Get Application Deployment Info
description: Gets information about the deployable

inputs:
  github-repository-name:
    description: "The GitHub repository name"
    required: true
  working-directory:
    description: "The working directory within the repository"
    required: true
  ecr-repository-name:
    description: "The ECR repository name (optional, will try this first for SSM path if provided)"
    required: false

outputs:
  ecs-cluster-name:
    description: The ECS Cluster Name
    value: ${{ steps.params.outputs.ecs_cluster_name }}
  ecs-service-name:
    description: The ECS Service Name
    value: ${{ steps.params.outputs.ecs_service_name }}
  ecs-container-name:
    description: The ECS Container Name
    value: ${{ steps.params.outputs.ecs_container_name }}
  ecr-image-base:
    description: The Image Base URL
    value: ${{ steps.params.outputs.ecr_image_base }}
  ecs-container-port:
    description: The container port to use
    value: ${{ steps.params.outputs.ecs_container_port }}
  static-files-bucket-name:
    description: The S3 Bucket Name for static files
    value: ${{ steps.frontend-params.outputs.static_files_bucket_name }}
  cloudfront-domain-name:
    description: The CloudFront Domain Name for a web application
    value: ${{ steps.frontend-params.outputs.cloudfront_domain_name }}
  central-deployment-account-id:
    description: The AWS Account ID to use for the central deployment account. Used for testing purposes
    value: ${{ steps.central-account.outputs.central_deployment_account_id }}

runs:
  using: composite
  steps:
    - name: Get Parameters
      id: params
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ inputs.github-repository-name }}
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
        ECR_REPOSITORY_NAME: ${{ inputs.ecr-repository-name }}
      # There is a bug here related to auto discovery.
      # When you have 1) a service that doesn't have an ECS service, i.e.
      # you're missing the expected SSM parameters.
      # 2) There are other ECS services in the account, we get the problem when there were >1,
      # but it's applicable for just 1 service too.
      # Then it will incorrectly identify those ECS services as matches in the auto-discovery
      # when they are not part of the correct Github repository or service.
      run: |
        GIT_REPO_NAME="${GITHUB_REPOSITORY##*/}"

        # Normalize working directory path
        WORKING_DIRECTORY="${WORKING_DIRECTORY#./}" # Remove leading ./
        WORKING_DIRECTORY="${WORKING_DIRECTORY#.}" # Remove leading .
        WORKING_DIRECTORY="${WORKING_DIRECTORY#/}" # Remove leading /

        # Build base path: repo/working-dir (or just repo if no working-dir)
        if [ -n "$WORKING_DIRECTORY" ]; then
          BASE_PATH="/__deployment__/${GIT_REPO_NAME}/${WORKING_DIRECTORY}"
        else
          BASE_PATH="/__deployment__/${GIT_REPO_NAME}"
        fi

        # Try with ECR name first, then fall back to base path (backward compatibility)
        if [ -n "$ECR_REPOSITORY_NAME" ]; then
          SSM_PATH="${BASE_PATH}/${ECR_REPOSITORY_NAME}"
          echo "Trying SSM path with ECR name: ${SSM_PATH}"
          PARAMS=$(aws ssm get-parameters-by-path --path "${SSM_PATH}/" --query "Parameters" 2>/dev/null || echo "[]")
          PARAM_COUNT=$(echo "$PARAMS" | jq '. | length')

          if [ "$PARAM_COUNT" -eq 0 ]; then
            echo "No parameters found with ECR name, falling back to base path: ${BASE_PATH}"
            SSM_PATH="${BASE_PATH}"
            PARAMS=$(aws ssm get-parameters-by-path --path "${SSM_PATH}/" --query "Parameters")
          else
            echo "Found $PARAM_COUNT parameter(s) using ECR repository name"
          fi
        else
          # No ECR name provided - try base path first (backward compat), then auto-discover
          SSM_PATH="${BASE_PATH}"
          echo "No ECR name provided, trying base path: ${SSM_PATH}"
          PARAMS=$(aws ssm get-parameters-by-path --path "${SSM_PATH}/" --query "Parameters" 2>/dev/null || echo "[]")
          PARAM_COUNT=$(echo "$PARAMS" | jq '. | length')

          if [ "$PARAM_COUNT" -eq 0 ]; then
            # No direct parameters - try to auto-discover from sub-paths
            echo "No parameters at base path, attempting auto-discovery..."

            ALL_PARAMS=$(aws ssm get-parameters-by-path \
              --path "${SSM_PATH}/" \
              --recursive \
              --query "Parameters[?ends_with(Name, '/ecs_service_name')].Name" \
              --output json 2>/dev/null || echo "[]")

            # Extract service names from the path after base
            SERVICE_NAMES=$(echo "$ALL_PARAMS" | jq -r --arg base "${SSM_PATH}/" '.[] | sub($base; "") | split("/")[0]' | sort -u)
            SERVICE_COUNT=$(echo "$SERVICE_NAMES" | grep -c . || echo "0")

            if [ "$SERVICE_COUNT" -eq 0 ]; then
              echo "::warning::No ECS services found"
              PARAMS="[]"
            elif [ "$SERVICE_COUNT" -eq 1 ]; then
              # Exactly one service found - use it
              DISCOVERED_ECR_NAME=$(echo "$SERVICE_NAMES" | head -n1)
              echo "Auto-discovered single service: ${DISCOVERED_ECR_NAME}"
              SSM_PATH="${BASE_PATH}/${DISCOVERED_ECR_NAME}"
              PARAMS=$(aws ssm get-parameters-by-path --path "${SSM_PATH}/" --query "Parameters")
            else
              # Multiple services - need explicit input
              echo "::error::Multiple ECS services found:"
              echo "$SERVICE_NAMES" | while read -r name; do
                [ -n "$name" ] && echo "::error::  - $name"
              done
              echo "::error::Please provide ecr-repository-names input in the workflow"
              exit 1
            fi
          fi
        fi

        PARAM_COUNT=$(echo "$PARAMS" | jq '. | length')
        if [ "$PARAM_COUNT" -eq 0 ]; then
          echo "::warning::No parameters found at ${SSM_PATH}"
        else
          echo "Found $PARAM_COUNT parameter(s)"
        fi

        for ROW in $(echo "$PARAMS" | jq -c '.[]'); do
          NAME=$(echo "$ROW" | jq -r '.Name' | rev | cut -d"/" -f1  | rev)
          echo "NAME=$NAME"
          VALUE=$(echo "$ROW" | jq -r '.Value')
          echo "VALUE=$VALUE"
          echo "$NAME=$VALUE" >> $GITHUB_OUTPUT
        done

    - name: Get Other parameters for ECS Service (Frontend SSR)
      id: frontend-params
      shell: bash
      if: steps.params.outputs.ecs_service_name != ''
      run: |
        ECS_SERVICE_NAME=${{ steps.params.outputs.ecs_service_name }}
        PARAMS=$(aws ssm get-parameters-by-path --path "/__deployment__/applications/${ECS_SERVICE_NAME}/" --query "Parameters")
        for ROW in $(echo "$PARAMS" | jq -c '.[]'); do
          NAME=$(echo "$ROW" | jq -r '.Name' | rev | cut -d"/" -f1  | rev)
          echo "NAME=$NAME"
          VALUE=$(echo "$ROW" | jq -r '.Value')
          echo "VALUE=$VALUE"
          echo "$NAME=$VALUE" >> $GITHUB_OUTPUT
        done

    - name: Get central deployment account ID
      id: central-account
      shell: bash
      run: |
        set +e
        CENTRAL_DEPLOYMENT_ACCOUNT_ID=$(aws ssm get-parameter --name "/__deployment__/applications/preview-url-mapper/central-deployment-account-id" --query "Parameter.Value" --output text)
        STATUS=$?
        
        if [ $STATUS -ne 0 ] || [ -z "$CENTRAL_DEPLOYMENT_ACCOUNT_ID" ]; then
          echo "No central deployment account ID found."
          exit 0
        fi
        
        echo "central_deployment_account_id=$CENTRAL_DEPLOYMENT_ACCOUNT_ID" >> $GITHUB_OUTPUT
