name: Get Application Deployment Info
description: Gets information about the deployable

inputs:
  github-repository-name:
    description: "The GitHub repository name"
    required: true
  working-directory:
    description: "The working directory within the repository"
    required: true
  ecr-repository-name:
    description: "The ECR repository name (optional, will try this first for SSM path if provided)"
    required: false

outputs:
  ecs-cluster-name:
    description: The ECS Cluster Name
    value: ${{ steps.params.outputs.ecs_cluster_name }}
  ecs-service-name:
    description: The ECS Service Name
    value: ${{ steps.params.outputs.ecs_service_name }}
  ecs-container-name:
    description: The ECS Container Name
    value: ${{ steps.params.outputs.ecs_container_name }}
  ecr-image-base:
    description: The Image Base URL
    value: ${{ steps.params.outputs.ecr_image_base }}
  ecs-container-port:
    description: The container port to use
    value: ${{ steps.params.outputs.ecs_container_port }}
  static-files-bucket-name:
    description: The S3 Bucket Name for static files
    value: ${{ steps.frontend-params.outputs.static_files_bucket_name }}
  cloudfront-domain-name:
    description: The CloudFront Domain Name for a web application
    value: ${{ steps.frontend-params.outputs.cloudfront_domain_name }}
  central-deployment-account-id:
    description: The AWS Account ID to use for the central deployment account. Used for testing purposes
    value: ${{ steps.central-account.outputs.central_deployment_account_id }}

runs:
  using: composite
  steps:
    - name: Get Parameters
      id: params
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ inputs.github-repository-name }}
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
        ECR_REPOSITORY_NAME: ${{ inputs.ecr-repository-name }}
      run: |
        GIT_REPO_NAME="${GITHUB_REPOSITORY##*/}"

        # Normalize working directory path
        WORKING_DIRECTORY="${WORKING_DIRECTORY#./}" # Remove leading ./
        WORKING_DIRECTORY="${WORKING_DIRECTORY#.}" # Remove leading .
        WORKING_DIRECTORY="${WORKING_DIRECTORY#/}" # Remove leading /

        # Build base path: repo/working-dir (or just repo if no working-dir)
        if [ -n "$WORKING_DIRECTORY" ]; then
          BASE_PATH="/__deployment__/${GIT_REPO_NAME}/${WORKING_DIRECTORY}"
        else
          BASE_PATH="/__deployment__/${GIT_REPO_NAME}"
        fi

        # Try with ECR name first, then fall back to base path (backward compatibility)
        if [ -n "$ECR_REPOSITORY_NAME" ]; then
          SSM_PATH="${BASE_PATH}/${ECR_REPOSITORY_NAME}"
          echo "Trying SSM path with ECR name: ${SSM_PATH}"
          PARAMS=$(aws ssm get-parameters-by-path --path "${SSM_PATH}/" --query "Parameters" 2>/dev/null || echo "[]")
          PARAM_COUNT=$(echo "$PARAMS" | jq '. | length')

          if [ "$PARAM_COUNT" -eq 0 ]; then
            echo "No parameters found with ECR name, falling back to base path: ${BASE_PATH}"
            SSM_PATH="${BASE_PATH}"
            PARAMS=$(aws ssm get-parameters-by-path --path "${SSM_PATH}/" --query "Parameters")
          else
            echo "Found $PARAM_COUNT parameter(s) using ECR repository name"
          fi
        else
          # No ECR name provided - use base path only (backward compatible)
          SSM_PATH="${BASE_PATH}"
          echo "Using base path (no ECR name): ${SSM_PATH}"
          PARAMS=$(aws ssm get-parameters-by-path --path "${SSM_PATH}/" --query "Parameters")
        fi

        PARAM_COUNT=$(echo "$PARAMS" | jq '. | length')
        if [ "$PARAM_COUNT" -eq 0 ]; then
          echo "::warning::No parameters found at ${SSM_PATH}"
        else
          echo "Found $PARAM_COUNT parameter(s)"
        fi

        for ROW in $(echo "$PARAMS" | jq -c '.[]'); do
          NAME=$(echo "$ROW" | jq -r '.Name' | rev | cut -d"/" -f1  | rev)
          echo "NAME=$NAME"
          VALUE=$(echo "$ROW" | jq -r '.Value')
          echo "VALUE=$VALUE"
          echo "$NAME=$VALUE" >> $GITHUB_OUTPUT
        done

    - name: Get Other parameters for ECS Service (Frontend SSR)
      id: frontend-params
      shell: bash
      if: steps.params.outputs.ecs_service_name != ''
      run: |
        ECS_SERVICE_NAME=${{ steps.params.outputs.ecs_service_name }}
        PARAMS=$(aws ssm get-parameters-by-path --path "/__deployment__/applications/${ECS_SERVICE_NAME}/" --query "Parameters")
        for ROW in $(echo "$PARAMS" | jq -c '.[]'); do
          NAME=$(echo "$ROW" | jq -r '.Name' | rev | cut -d"/" -f1  | rev)
          echo "NAME=$NAME"
          VALUE=$(echo "$ROW" | jq -r '.Value')
          echo "VALUE=$VALUE"
          echo "$NAME=$VALUE" >> $GITHUB_OUTPUT
        done

    - name: Get central deployment account ID
      id: central-account
      shell: bash
      run: |
        set +e
        CENTRAL_DEPLOYMENT_ACCOUNT_ID=$(aws ssm get-parameter --name "/__deployment__/applications/preview-url-mapper/central-deployment-account-id" --query "Parameter.Value" --output text)
        STATUS=$?
        
        if [ $STATUS -ne 0 ] || [ -z "$CENTRAL_DEPLOYMENT_ACCOUNT_ID" ]; then
          echo "No central deployment account ID found."
          exit 0
        fi
        
        echo "central_deployment_account_id=$CENTRAL_DEPLOYMENT_ACCOUNT_ID" >> $GITHUB_OUTPUT
