name: Get Application Deployment Info
description: Gets information about the deployable

inputs:
  application-name:
    description: "The name of the application"

outputs:
  compute-target:
    description: What kind of compute we are targeting (ECS or Lambda)
    value: ${{ steps.params.outputs.compute_target }}
  codedeploy-deployment-group:
    description: The CodeDeploy Deployment Group
    value: ${{ steps.params.outputs.codedeploy_deployment_group }}
  codedeploy-application-name:
    description: The CodeDeploy Applicaion Name
    value: ${{ steps.params.outputs.codedeploy_application_name }}
  ecs-cluster-name:
    description: The ECS Cluster Name
    value: ${{ steps.params.outputs.ecs_cluster_name }}
  ecs-service-name:
    description: The ECS Service Name
    value: ${{ steps.params.outputs.ecs_service_name }}
  ecs-container-name:
    description: The ECS Container Name
    value: ${{ steps.params.outputs.ecs_container_name }}
  ecr-image-base:
    description: The Image Base URL
    value: ${{ steps.params.outputs.ecr_image_base }}
  ecs-container-port:
    description: The container port to use
    value: ${{ steps.params.outputs.ecs_container_port }}
  lambda-function-name:
    description: The name of the Lambda function
    value: ${{ steps.params.outputs.lambda_function_name }}
  lambda-s3-bucket:
    description: The S3 Bucket Name
    value: ${{ steps.params.outputs.lambda_s3_bucket }}
  lambda-s3-folder:
    description: The folder within the S3 Bucket
    value: ${{ steps.params.outputs.lambda_s3_folder }}
  lambda-ecr-image-base:
    description: The ECR Image URI for the Lambda function
    value: ${{ steps.params.outputs.lambda_ecr_image_base }}
  static-files-bucket-name:
    description: The S3 Bucket Name for static files
    value: ${{ steps.params.outputs.static_files_bucket_name }}
  cloudfront-domain-name:
    description: The CloudFront Domain Name for a web application
    value: ${{ steps.params.outputs.cloudfront_domain_name }}
  central-deployment-account-id:
    description: The AWS Account ID to use for the central deployment account. Used for testing purposes
    value: ${{ steps.central-account.outputs.central_deployment_account_id }}

runs:
  using: composite
  steps:
    - name: Get Parameters
      id: params
      shell: bash
      run: |
        PARAMS=$(aws ssm get-parameters-by-path --path "/__deployment__/applications/${{ inputs.application-name }}/" --query "Parameters")
        for ROW in $(echo "$PARAMS" | jq -c '.[]'); do
          NAME=$(echo "$ROW" | jq -r '.Name' | rev | cut -d"/" -f1  | rev)
          echo "NAME=$NAME"
          VALUE=$(echo "$ROW" | jq -r '.Value')
          echo "VALUE=$VALUE"
          echo "$NAME=$VALUE" >> $GITHUB_OUTPUT
        done

    - name: Get central deployment account ID
      id: central-account
      shell: bash
      run: |
        CENTRAL_DEPLOYMENT_ACCOUNT_ID=$(aws ssm get-parameter --name "/__deployment__/applications/preview-url-mapper/central-deployment-account-id" --query "Parameter.Value" --output text)
        echo "central_deployment_account_id=$CENTRAL_DEPLOYMENT_ACCOUNT_ID" >> $GITHUB_OUTPUT
