name: Get Application Deployment Info
description: Gets information about the deployable

inputs:
  github-repository-name:
    description: "The GitHub repository name"
    required: true
  working-directory:
    description: "The working directory within the repository"
    required: true

outputs:
  ecs-cluster-name:
    description: The ECS Cluster Name
    value: ${{ steps.params.outputs.ecs_cluster_name }}
  ecs-service-name:
    description: The ECS Service Name
    value: ${{ steps.params.outputs.ecs_service_name }}
  ecs-container-name:
    description: The ECS Container Name
    value: ${{ steps.params.outputs.ecs_container_name }}
  ecr-image-base:
    description: The Image Base URL
    value: ${{ steps.params.outputs.ecr_image_base }}
  ecs-container-port:
    description: The container port to use
    value: ${{ steps.params.outputs.ecs_container_port }}
  static-files-bucket-name:
    description: The S3 Bucket Name for static files
    value: ${{ steps.params.outputs.static_files_bucket_name }}
  cloudfront-domain-name:
    description: The CloudFront Domain Name for a web application
    value: ${{ steps.params.outputs.cloudfront_domain_name }}
  central-deployment-account-id:
    description: The AWS Account ID to use for the central deployment account. Used for testing purposes
    value: ${{ steps.central-account.outputs.central_deployment_account_id }}

runs:
  using: composite
  steps:
    - name: Get Parameters
      id: params
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ inputs.github-repository-name }}
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
      run: |
        GIT_REPO_NAME="${GITHUB_REPOSITORY##*/}"
        PARAMS=$(aws ssm get-parameters-by-path --path "/__deployment__/${GIT_REPO_NAME}/${WORKING_DIRECTORY}" --query "Parameters")
        for ROW in $(echo "$PARAMS" | jq -c '.[]'); do
          NAME=$(echo "$ROW" | jq -r '.Name' | rev | cut -d"/" -f1  | rev)
          echo "NAME=$NAME"
          VALUE=$(echo "$ROW" | jq -r '.Value')
          echo "VALUE=$VALUE"
          echo "$NAME=$VALUE" >> $GITHUB_OUTPUT
        done

    - name: Get central deployment account ID
      id: central-account
      shell: bash
      run: |
        set +e
        CENTRAL_DEPLOYMENT_ACCOUNT_ID=$(aws ssm get-parameter --name "/__deployment__/applications/preview-url-mapper/central-deployment-account-id" --query "Parameter.Value" --output text)
        STATUS=$?
        
        if [ $STATUS -ne 0 ] || [ -z "$CENTRAL_DEPLOYMENT_ACCOUNT_ID" ]; then
          echo "No central deployment account ID found."
          exit 0
        fi
        
        echo "central_deployment_account_id=$CENTRAL_DEPLOYMENT_ACCOUNT_ID" >> $GITHUB_OUTPUT
