name: Get All Environments in this repository

outputs:
  environments:
    description: 'All environments in this repository.'
    value: ${{ steps.get-environments.outputs.environments }}

runs:
  using: composite
  steps:
    - name: Get All Environments in Repository
      id: get-environments
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -e
        environments=$(gh api --method GET -H "Accept: application/vnd.github+json" repos/${{ github.repository}}/environments | jq -c '[.environments[].name]')
        if [ -z "$environments" ] || [ "$environments" = "[]" ]; then
          echo "::error title=No environments found::Check if you have any GitHub environments configured."
          exit 1
        fi
        echo "environments=${environments}" >> $GITHUB_OUTPUT