name: Get All Environments in this repository

inputs:
  skip-service-environment:
    description: 'Skip deployment to the service environment. Use if the repository does not deploy to the service environment.'
    required: true

outputs:
  environments:
    description: 'All environments in this repository.'
    value: ${{ steps.get-environments.outputs.environments }}

runs:
  using: composite
  steps:
    - name: Get All Environments in Repository
      id: get-environments
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -e
        environments=$(gh api --method GET -H "Accept: application/vnd.github+json" repos/${{ github.repository}}/environments | jq -c '[.environments[].name]')
        if [ -z "$environments" ] || [ "$environments" = "[]" ]; then
          echo "::error title=No environments found::Check if you have any GitHub environments configured."
          exit 1
        fi
        if [ "${{ inputs.skip-service-environment }}" = "true" ]; then
          # Filter out the "service" case insensitive environment if it exists
          environments=$(echo "$environments" | jq 'map(select(test("^service$"; "i") | not))')
        fi
        echo "environments=$(echo "$environments" | jq 'map(select(test("^preview$"; "i") | not))' | jq -c)" >> $GITHUB_OUTPUT