name: Gradle
description: Run Gradle Commands

inputs:
  NEXUS_USERNAME:
    required: true
    description: "Nexus login username."
  NEXUS_PASSWORD:
    required: true
    description: "Nexus login password."
  BUILD_CACHE_USERNAME:
    required: false
    default: ""
    description: "Optional Gradle build cache username."
  BUILD_CACHE_PASSWORD:
    required: false
    default: ""
    description: "Optional Gradle build cache password."
  GRADLE_CACHE_ENCRYPTION_KEY:
    required: false
    description: "Key to use for encrypting the configuration cache."
    default: ""

  gradle-operations:
    required: true
    description: "What gradle operations to execute."

  java-version:
    required: true
    description: "What Java version to use."
  java-distribution:
    required: false
    default: "temurin"
    description: "What Java distribution to use. Default is temurin (By Adoptium)."

  working-directory:
    required: false
    default: "."
    description: "Where gradle will be run from."

  cache-read-only:
    required: false
    default: "false"
    description: "When true, existing cache entries will be read but no new cache entries will be written."

runs:
  using:
    composite
  steps:
    - name: Debug Java Version
      shell: bash
      run: |
        echo "Java version: ${{ inputs.java-version }}"

    - name: Set Up Java
      uses: actions/setup-java@v5
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ inputs.cache-read-only }}
        cache-encryption-key: ${{ inputs.GRADLE_CACHE_ENCRYPTION_KEY }}
        gradle-home-cache-includes: |
          caches
          notifications
        gradle-home-cache-excludes: |
          caches/modules-2/modules-2.lock
          caches/modules-2/gc.properties
          caches/build-cache-*
          caches/keyrings

    - name: Run Gradle Command
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        repo: ${{ github.event.repository.name }}
        gradle-operations: ${{ inputs.gradle-operations }}
        NEXUS_USERNAME: ${{ inputs.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ inputs.NEXUS_PASSWORD }}
        BUILD_CACHE_USERNAME: ${{ inputs.BUILD_CACHE_USERNAME }}
        BUILD_CACHE_PASSWORD: ${{ inputs.BUILD_CACHE_PASSWORD }}
      run: |
        ./gradlew ${{ inputs.gradle-operations }}
