name: Gradle
description: Run Gradle Commands

inputs:
  NEXUS_USERNAME:
    required: true
    description: "Nexus login username."
  NEXUS_PASSWORD:
    required: true
    description: "Nexus login password."

  gradle-operations:
    required: true
    description: "What gradle operations to execute."

  java-version:
    required: true
    description: "What Java version to use."
  java-distribution:
    required: false
    default: "temurin"
    description: "What Java distribution to use. Default is temurin (By Adoptium)."

  working-directory:
    required: false
    default: "."
    description: "Where gradle will be run from."

runs:
  using:
    composite
  steps:
    - name: Debug Java Version
      shell: bash
      run: | 
        echo "Java version: ${{ inputs.java-version }}"

    - name: Set Up Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false # enables caching on all branches, not just master

    - name: Run Gradle Command
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        repo: ${{ github.event.repository.name }}
        gradle-operations: ${{ inputs.gradle-operations }}
        NEXUS_USERNAME: ${{ inputs.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ inputs.NEXUS_PASSWORD }}
      run: |
        ./gradlew ${{ inputs.gradle-operations }}
