name: PNPM Action

inputs:
  NEXUS_USERNAME:
    required: true
    description: "Nexus login username."
  NEXUS_PASSWORD:
    required: true
    description: "Nexus login password."

  node-version:
    required: true
    description: "What Node.js version to use."
  pnpm-version:
    required: false
    default: "10"
    description: "What pnpm version to use. Default is 10."
  pnpm-operations:
    required: true
    description: "pnpm operations to run."
  working-directory:
    required: false
    default: "."
    description: "Where pnpm will be run from."
  git-sha:
    required: true
    description: "Git SHA to use for versioning"

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: '${{ inputs.working-directory }}/pnpm-lock.yaml'

    - name: Run pnpm Install
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        NEXUS_USERNAME: ${{ inputs.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ inputs.NEXUS_PASSWORD }}
      run: |
        pnpm install --frozen-lockfile

    - name: Run pnpm Command
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        pnpm-operations: ${{ inputs.pnpm-operations }}
        NEXUS_USERNAME: ${{ inputs.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ inputs.NEXUS_PASSWORD }}
        GIT_SHA: ${{ inputs.git-sha }}
      run: |
        pnpm run ${{ inputs.pnpm-operations }}
