on:
  workflow_call:
    secrets:
      NEXUS_USERNAME:
        required: true
        description: "Nexus login username."
      NEXUS_PASSWORD:
        required: true
        description: "Nexus login password."

    inputs:
      java-version:
        required: false
        type: string
        description: "What Java version to use."
        default: "17"
      java-distribution:
        required: false
        type: string
        default: "temurin"
        description: "What Java distribution to use. Default is temurin (By Adoptium)."
      working-directory:
        required: false
        type: string
        default: "."
      artifact-name:
        required: false
        type: string
        default: "application-build"
      artifact-path:
        required: false
        type: string
        default: "./build"  # Default for Gradle.
      gradle-operations:
        required: false
        type: string
        default: "assemble --build-cache"
        description: "Gradle operations to run."
      git-sha:
        required: false
        type: string
        default: ${{ github.event.pull_request.head.sha || github.sha }}

    outputs:
      artifact-name:
        description: The name of the artifact generated by the build
        value: ${{ inputs.artifact-name }}
      artifact-path:
        description: Where the artifact is stored in the working directory.
        value: ${{ inputs.artifact-path }}

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0' # Fetch all history for all branches and tags (for branches)
          ref: ${{ inputs.git-sha }}

      - uses: nsbno/platform-actions/.github/actions/tools/gradle@v1
        name: Gradle Build
        with:
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          gradle-operations: ${{ inputs.gradle-operations }}
          working-directory: ${{ inputs.working-directory }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          # if exists
          BUILD_CACHE_PASSWORD: ${{ secrets.BUILD_CACHE_PASSWORD }}
          BUILD_CACHE_USERNAME: ${{ secrets.BUILD_CACHE_USERNAME }}
          GRADLE_CACHE_ENCRYPTION_KEY: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}

      - name: Store built JAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 5
