name: Terraform Plan on comment
on:
  workflow_call:
    inputs:
      working-directory:
        description: "Directory containing the project files"
        required: false
        type: string
        default: "."
      terraform-directory:
        description: Directory where Terraform environment directories are located
        type: string
        required: false
        default: ''
      skip-service-environment:
        description: Skip the service environment, if the repository does not deploy to the service environment.
        type: boolean
        default: false
        required: false

jobs:
  trigger:
    # Own implementation of trigger which is not branch-deploy because of message body customization
    name: Trigger .tf plan
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '.tf plan')
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
    outputs:
      sha: ${{ env.GIT_SHA }}
      issue_number: ${{ steps.ids.outputs.issue_number }}
      comment_id: ${{ steps.ids.outputs.comment_id }}
    steps:
      - id: ids
        run: |
          echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          echo "comment_id=${{ github.event.comment.id }}" >> $GITHUB_OUTPUT

      - name: Add eyes reaction to triggering comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method POST \
            repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions \
            -f content='eyes'

      - name: Comment plan is running
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Terraform plan initiated for commit `${{ env.GIT_SHA }}`.
            
            • Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            • Triggered by: @${{ github.actor }}

  react-rocket:
    name: React rocket
    needs: trigger
    runs-on: ubuntu-latest
    steps:
      - name: Add rocket reaction to triggering comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method POST \
            repos/${{ github.repository }}/issues/comments/${{ needs.trigger.outputs.comment_id }}/reactions \
            -f content='rocket'

  plan:
    needs: trigger
    uses: nsbno/platform-actions/.github/workflows/helpers.terraform-plan.yml@main
    with:
      working-directory: ${{ inputs.working-directory }}
      terraform-directory: ${{ inputs.terraform-directory }}
      skip-service-environment: ${{ inputs.skip-service-environment }}
      git-sha: ${{ needs.trigger.outputs.sha }}

