on:
  workflow_call:
    inputs:
      force-deploy:
        description:  Makes sure that terraform deploy always happens
        type: boolean
        default: false
        required: false
      working-directory:
        description: "Directory containing the project files"
        required: false
        type: string
        default: "."
      terraform-directory:
        description: Directory where Terraform environment directories are located
        type: string
        required: false
        default: ''
      skip-service-environment:
        description: Skip the service environment, if the repository does not deploy to the service environment.
        type: boolean
        default: false
        required: false
      git-sha:
        description: The SHA to find changes to. First try the current head of PR.
        type: string
        required: false
        default: ${{ github.event.pull_request.head.sha || github.sha }}

    outputs:
      # A list with names of which environments as changes
      has-changes:
        description: 'List of environments with changes'
        value: ${{ jobs.create-terraform-changes-list.outputs.changes }}

name: Find Terraform Changes

jobs:
  get-environments:
    if: ${{ !inputs.force-deploy }}
    name: Find Relevant GH Environments
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.envs.outputs.environments }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: nsbno/platform-actions/.github/actions/helpers/get-environments@v1
        id: envs
        with:
          skip-service-environment: ${{ inputs.skip-service-environment }}

  has-terraform-changed:
    name: Detect Changes
    needs: get-environments
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ fromJson(needs.get-environments.outputs.environments) }}
    environment: ${{ matrix.environment }}
    # Needed to avoid conflicts with terraform state
    concurrency:
      group: ${{ inputs.working-directory }}-${{ matrix.environment }}-terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0' # Fetch all history for all branches and tags (for branch deploys)
          ref: ${{ inputs.git-sha }}

      - name: Run Terraform Plan
        uses: nsbno/platform-actions/.github/actions/helpers/has-terraform-changed@v1
        id: changed-files
        with:
          environment: ${{ matrix.environment }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-account-id: ${{ vars.AWS_ACCOUNT_ID }}
          deployment-role: ${{ vars.AWS_DEPLOYMENT_ROLE_NAME }}
          working-directory: ${{ inputs.working-directory }}
          terraform-directory: ${{ inputs.terraform-directory }}

      - name: Notify about changes
        shell: bash
        run: |
          if ${{ steps.changed-files.outputs.any-changed }}; then
            echo "::notice title=Changes to Terraform::${{ matrix.environment}} has changes and will be deployed 🚀"
          else
            echo "::notice title=Changes to Terraform::${{ matrix.environment}} has no changes, and will not be deployed 💤"
          fi

      - name: Set output
        shell: bash
        run: |
          mkdir -p ./matrix-outputs
          echo "${{ steps.changed-files.outputs.any-changed }}" > ./matrix-outputs/${{ matrix.environment }}.txt

      - name: Determine working directory name for artifacts
        id: without-slashes
        run: |
          WORKING_DIRECTORY="${{ inputs.working-directory }}"
          # Replace slashes with dashes to avoid issues with artifact names
          NAME_WITHOUT_SLASHES="${WORKING_DIRECTORY//\//-}"
          echo "working-directory=$NAME_WITHOUT_SLASHES" >> $GITHUB_OUTPUT
  
      - name: Upload matrix outputs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.without-slashes.outputs.working-directory }}-matrix-outputs-${{ matrix.environment }}
          path: ./matrix-outputs
          retention-days: 1
          overwrite: true

  create-terraform-changes-list:
    name: Aggregate Changes
    needs:
      - has-terraform-changed
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.aggregate.outputs.CHANGES }}
    steps:
      - name: Determine working directory name for artifacts
        id: without-slashes
        run: |
          WORKING_DIRECTORY="${{ inputs.working-directory }}"
          # Replace slashes with dashes to avoid issues with artifact names
          NAME_WITHOUT_SLASHES="${WORKING_DIRECTORY//\//-}"
          echo "working-directory=$NAME_WITHOUT_SLASHES" >> $GITHUB_OUTPUT

      - name: Download matrix outputs
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ steps.without-slashes.outputs.working-directory }}-matrix-outputs-*
          merge-multiple: true
          path: ./matrix-outputs

      - name: Aggregate environment changes
        id: aggregate
        run: |
          # One-liner to create JSON array of environments with changes
          CHANGES=$(grep -l "true" ./matrix-outputs/*.txt | sed -E 's/.*\/(.*)\.txt/\1/' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          
          echo "Following environments have changes: ${CHANGES}"
          echo "CHANGES=${CHANGES}" >> $GITHUB_OUTPUT
