# Instead of storing the DataDog CI API key directly in
# GitHub, we persist it in AWS so that autorotation
# of the value is much easeier.
# But this requires a workflow which makes it easy for others to retrieve the key
name: Retrieve Datadog CI API Key

on:
  workflow_call:
    inputs:
      secret-id:
        required: false
        description: '(Optional) Id to the DataDog CI API key. Override only if you have a custom key'
        type: string
        default: ${{ vars.DATADOG_CI_API_KEY_SECRET_ID }}
    outputs:
      datadog-api-key:
        description: 'Datadog CI API key. Useful when you want to upload source-maps to DataDog, or any other CI operations'
        value: ${{ jobs.fetch-key.outputs.api-key }}

jobs:
  fetch-key:
    runs-on: ubuntu-latest
    # Need access to an environment context to fetch AWS credentials
    environment: Service
    permissions:
      id-token: write
      contents: read
    outputs:
      api-key: ${{ steps.secrets.outputs.secret-value }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_DEPLOYMENT_ROLE_NAME }}"

      - uses: nsbno/platform-actions/.github/actions/helpers/aws/fetch-secrets-from-secrets-manager@datadog-ci-workflows
        id: secrets
        with:
          secret-id: ${{ inputs.secret-id }}
