name: Terraform Plan on comment
on:
  workflow_call:
    inputs:
      working-directory:
        description: "Directory containing the project files"
        required: false
        type: string
        default: "."
      terraform-directory:
        description: Directory where Terraform environment directories are located
        type: string
        required: false
        default: ''
      skip-service-environment:
        description: Skip the service environment, if the repository does not deploy to the service environment.
        type: boolean
        default: false
        required: false

jobs:
  trigger:
    # Own implementation of trigger which is not branch-deploy because of message body customization
    name: Trigger .tf plan
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '.tf plan')
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      git_sha: ${{ steps.get-sha.outputs.sha }}
      issue_number: ${{ steps.ids.outputs.issue_number }}
      comment_id: ${{ steps.ids.outputs.comment_id }}
    steps:
      - id: ids
        run: |
          echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          echo "comment_id=${{ github.event.comment.id }}" >> $GITHUB_OUTPUT

      - name: Determine PR SHA
        id: get-sha
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          SHA=$(gh api repos/${{ github.repository }}/pulls/$PR_NUMBER --jq .head.sha)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Add eyes reaction to triggering comment
        run: |
          gh api \
            --method POST \
            repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions \
            -f content='eyes'

      - name: Comment plan is running
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ### Terraform plan initiated
            
            🔗 [Follow the plan here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
            Commit: [${{ steps.get-sha.outputs.sha }}](${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.issue.number }}/commits/${{ steps.get-sha.outputs.sha }})
            
            _If you see a 🚀 on your comment and no Terraform Plan output, it means no changes were detected._

  plan:
    needs: trigger
    uses: nsbno/platform-actions/.github/workflows/helpers.terraform-plan.yml@main
    with:
      working-directory: ${{ inputs.working-directory }}
      terraform-directory: ${{ inputs.terraform-directory }}
      skip-service-environment: ${{ inputs.skip-service-environment }}
      git-sha: ${{ needs.trigger.outputs.git_sha }}

  reaction-handling:
    name: Remove eyes, React rocket
    needs:
      - trigger
      - plan
    runs-on: ubuntu-latest
    steps:
      - name: Remove eyes reaction from triggering comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          REACTION_ID=$(gh api \
            repos/${{ github.repository }}/issues/comments/${{ needs.trigger.outputs.comment_id }}/reactions \
            | jq -r '.[] | select(.content == "eyes") | .id' | head -n 1)

          if [ -n "$REACTION_ID" ]; then
            gh api \
              --method DELETE \
              repos/${{ github.repository }}/issues/comments/${{ needs.trigger.outputs.comment_id }}/reactions/$REACTION_ID
          else
            echo "No 'eyes' reaction found to remove."
          fi

      - name: Add rocket reaction to triggering comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method POST \
            repos/${{ github.repository }}/issues/comments/${{ needs.trigger.outputs.comment_id }}/reactions \
            -f content='rocket'