name: node test

on:
  workflow_call:
    secrets:
      NEXUS_USERNAME:
        required: true
        description: "Nexus login username."
      NEXUS_PASSWORD:
        required: true
        description: "Nexus login password."

    inputs:
      node-version:
        required: false
        type: string
        description: "What Node.js version to use."
        default: "20"
      package-manager:
        required: false
        type: string
        description: "Package manager to use. Default is pnpm."
        default: "pnpm"
      working-directory:
        required: false
        type: string
        default: "."
      artifact-name:
        required: false
        type: string
        default: ""
      artifact-path:
        required: false
        type: string
        default: "" # What to upload as artifact

jobs:
  test:
    name: node test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Artifact
        if: inputs.artifact-name != ''
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}

      - name: Check package manager
        run: |
          if [[ "${{ inputs.package-manager }}" != "npm" && "${{ inputs.package-manager }}" != "pnpm" ]]; then
            echo "Unsupported package manager: ${{ inputs.package-manager }}"
            exit 1
          fi

      - uses: nsbno/platform-actions/.github/actions/tools/npm@main
        if: ${{ inputs.package-manager == 'npm' }}
        name: npm test
        with:
          node-version: ${{ inputs.node-version }}
          npm-operations: test
          working-directory: ${{ inputs.working-directory }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

      - uses: nsbno/platform-actions/.github/actions/tools/pnpm@main
        if: ${{ inputs.package-manager == 'pnpm' }}
        name: pnpm test
        with:
          node-version: ${{ inputs.node-version }}
          pnpm-operations: test
          working-directory: ${{ inputs.working-directory }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
